# Generated by Django 5.1.1 on 2024-09-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Add', models.CharField(max_length=50)),
                ('Mob', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Csit',
            },
        ),
    ]
