# Generated by Django 5.1.1 on 2024-09-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NpjAirport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csit',
            old_name='Mob',
            new_name='Phone',
        ),
    ]
