# Generated by Django 5.1.1 on 2024-09-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NpjAirport', '0002_rename_mob_csit_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csit',
            name='Add',
        ),
    ]
